<a href="https://colab.research.google.com/github/Dargesen004/GithubLearning/blob/main/titanic_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Titaniko analize

Cia kazkoks aprasymas. Duomenis paemem [cia](https://www.kaggle.com/competitions/titanic).
- irasas
- irasas
- irasas

In [30]:
import csv

survived_list = []
fare_list = []

with open("titanic.csv", newline="") as csvfile:
    reader = csv.reader(csvfile, delimiter=",")
    next(reader)

    for line in reader:
        survived_list.append(int(line[0]))
        fare_list.append(float(line[6]))
print(survived_list)
print(fare_list)
[0, 1, 1, 0, 0]




[0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 

[0, 1, 1, 0, 0]

In [15]:
fare_list

[7.25,
 71.2833,
 7.925,
 53.1,
 8.05,
 8.4583,
 51.8625,
 21.075,
 11.1333,
 30.0708,
 16.7,
 26.55,
 8.05,
 31.275,
 7.8542,
 16.0,
 29.125,
 13.0,
 18.0,
 7.225,
 26.0,
 13.0,
 8.0292,
 35.5,
 21.075,
 31.3875,
 7.225,
 263.0,
 7.8792,
 7.8958,
 27.7208,
 146.5208,
 7.75,
 10.5,
 82.1708,
 52.0,
 7.2292,
 8.05,
 18.0,
 11.2417,
 9.475,
 21.0,
 7.8958,
 41.5792,
 7.8792,
 8.05,
 15.5,
 7.75,
 21.6792,
 17.8,
 39.6875,
 7.8,
 76.7292,
 26.0,
 61.9792,
 35.5,
 10.5,
 7.2292,
 27.75,
 46.9,
 7.2292,
 80.0,
 83.475,
 27.9,
 27.7208,
 15.2458,
 10.5,
 8.1583,
 7.925,
 8.6625,
 10.5,
 46.9,
 73.5,
 14.4542,
 56.4958,
 7.65,
 7.8958,
 8.05,
 29.0,
 12.475,
 9.0,
 9.5,
 7.7875,
 47.1,
 10.5,
 15.85,
 34.375,
 8.05,
 263.0,
 8.05,
 8.05,
 7.8542,
 61.175,
 20.575,
 7.25,
 8.05,
 34.6542,
 63.3583,
 23.0,
 26.0,
 7.8958,
 7.8958,
 77.2875,
 8.6542,
 7.925,
 7.8958,
 7.65,
 7.775,
 7.8958,
 24.15,
 52.0,
 14.4542,
 8.05,
 9.825,
 14.4583,
 7.925,
 7.75,
 21.0,
 247.5208,
 31.275,
 73.5,
 8.05,


In [16]:
survived_list

[0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,


In [17]:
import csv
from statistics import mean

# kiek procentu zmoniu isgyveno?
sprob_survival = survived_list.count(1) / len(survived_list)
print(f"Probability of survival in Titanic: {sprob_survival}")

# kokia vidutine kaina Titaniko bilieto?
fare_list = list(filter(lambda x: x > 0 , fare_list)) # filter out all of zero fares
fare_mean = mean(fare_list)
print(f"The mean price of a Titanic tiscket is: {fare_mean:.2f}")
print(f"The min price of a Titanic tiscket is: {min(fare_list):.2f}")
print(f"The max price of a Titanic tiscket is: {max(fare_list):.2f}")



Probability of survival in Titanic: 0.3838383838383838
The mean price of a Titanic tiscket is: 32.76
The min price of a Titanic tiscket is: 4.01
The max price of a Titanic tiscket is: 512.33


In [18]:
import csv
from statistics import mean

# kiek procentu zmoniu isgyveno?
sprob_survival = survived_list.count(1) / len(survived_list)
print(f"Probability of survival in Titanic: {sprob_survival}")




Probability of survival in Titanic: 0.3838383838383838


we want to compute the mean probability of survival

$p(x) \sim = \frac{sum

In [27]:
import numpy as np


In [38]:
fare_list = np.array(fare_list)

In [32]:
list(range(4,22,2))

[4, 6, 8, 10, 12, 14, 16, 18, 20]

In [39]:
np.arange(0,30,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [42]:
np.linspace(4,22,4)

array([ 4., 10., 16., 22.])

In [43]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [47]:
np.random.rand(10)

array([0.65503534, 0.22788851, 0.80027861, 0.28130376, 0.34105854,
       0.49296615, 0.75934131, 0.49054756, 0.56547397, 0.22100439])

In [49]:
np.random.randn(10)

array([-0.4673913 , -0.65722686,  0.65700956, -0.24055484,  1.08686023,
       -0.23705528, -0.1052717 ,  0.23592454,  1.56922158,  0.51880216])

In [60]:
np.random.randint(0,100,10)

array([58, 76, 85, 83, 92,  0,  0, 31, 73, 90])

In [63]:
vec = np.random.rand(10)
vec.shape

(10,)

In [65]:
vec.reshape(2,5).reshape

<function ndarray.reshape>

In [67]:
type(fare_list)

numpy.ndarray

In [70]:
fare_list.min()


np.float64(0.0)

In [72]:
fare_list.max()


np.float64(512.3292)

In [77]:
print(fare_list.argmin())
print(fare_list[fare_list.argmin()])


179
0.0


In [84]:
first_ten =  fare_list  [:10]
first_ten


array([ 7.25  , 71.2833,  7.925 , 53.1   ,  8.05  ,  8.4583, 51.8625,
       21.075 , 11.1333, 30.0708])

In [87]:
bool_mask = (fare_list < 10)[:10]
bool_mask

array([ True, False,  True, False,  True,  True, False, False, False,
       False])

In [89]:
first_ten[bool_mask]

array([7.25  , 7.925 , 8.05  , 8.4583])

In [91]:
first_ten[first_ten < 10]

array([7.25  , 7.925 , 8.05  , 8.4583])

In [93]:
first_ten + 10

array([17.25  , 81.2833, 17.925 , 63.1   , 18.05  , 18.4583, 61.8625,
       31.075 , 21.1333, 40.0708])

In [95]:
[1,2,3] + [2,3,4]

[1, 2, 3, 2, 3, 4]

In [97]:
np.array([1,2,3]) + np.array([2,3,4])

array([3, 5, 7])

In [101]:
numbers = np.array([1,2,3])
numbers

array([1, 2, 3])

In [105]:
np.sin(np.arange(4))

array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [106]:
[np.sin(x) for x in range (1,4)]

[np.float64(0.8414709848078965),
 np.float64(0.9092974268256817),
 np.float64(0.1411200080598672)]