<a href="https://colab.research.google.com/github/Dargesen004/GithubLearning/blob/main/uzduotys.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones(10)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.full(10,4)

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [17]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [41]:
matrica = np.arange(1,26).reshape(5,5)
matrica


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [48]:
matrica[2,1]

np.int64(12)

In [50]:
matrica[4]

array([21, 22, 23, 24, 25])

In [57]:
submatrica = matrica[0:3,0:3]
submatrica

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [61]:
matrica[1:4,1:5]

array([[ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20]])

In [81]:
matrica[3:, :3]

array([[16, 17, 18],
       [21, 22, 23]])

In [84]:
atsitiktinis = np.random.rand(20)
atsitiktinis

array([0.77748865, 0.99007128, 0.20250507, 0.76095894, 0.18640524,
       0.98690049, 0.4310809 , 0.08178541, 0.56143102, 0.73423613,
       0.92278483, 0.26159534, 0.82609267, 0.25740754, 0.79445625,
       0.51838844, 0.54149297, 0.89585294, 0.19553979, 0.34384141])

In [86]:
atsitiktinis.max()

np.float64(0.9900712761680592)